import turtle
wn=turtle.Screen()
panda=turtle.Turtle()
panda.pensize(3)
panda.speed(10)
panda.fillcolor("white")
panda.begin_fill()
panda.circle(60)
panda.end_fill()

panda.up()
panda.setpos(-45,100)
panda.down()
panda.fillcolor('black')
panda.begin_fill()
panda.circle(20)
panda.end_fill()

panda.up()
panda.setpos(45,100)
panda.down()
panda.fillcolor('black')
panda.begin_fill()
panda.circle(20)
panda.end_fill()

panda.up()
panda.setpos(-25,70)
panda.down()
panda.fillcolor('black')
panda.begin_fill()
panda.circle(10)
panda.end_fill()

panda.up()
panda.setpos(25,70)
panda.down()
panda.fillcolor('black')
panda.begin_fill()
panda.circle(10)
panda.end_fill()

panda.up()
panda.setpos(-25,72)
panda.down()
panda.fillcolor('white')
panda.begin_fill()
panda.circle(6)
panda.end_fill()

panda.up()
panda.setpos(25,72)
panda.down()
panda.fillcolor('white')
panda.begin_fill()
panda.circle(6)
panda.end_fill()

panda.up()
panda.setpos(0,40)
panda.down()
panda.fillcolor('black')
panda.begin_fill()
panda.circle(7)
panda.end_fill()

panda.up()
panda.setpos(0,40)
panda.down()
panda.right(90)
panda.circle(7,180)

panda.up()
panda.setpos(0,40)
panda.down()
panda.left(360)
panda.circle(7,-180)
panda.hideturtle()
wn.exitonclick()
